project:
  type: website
  title: "Building Agentic AI Systems"
  preview:
    port: 4700
  output-dir: _site

website:
  navbar:
    left:
      - href: index.qmd
        text: "Home"

execute:
  # https://quarto.org/docs/computations/python.html#kernel-daemon
  daemon: 300
  
  # https://quarto.org/docs/computations/caching.html#jupyter-cache
  cache: true

  # https://quarto.org/docs/publishing/github-pages.html#freezing-computations
  freeze: auto


format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Contents"
    anchor-sections: true
    smooth-scroll: true
    mermaid: 
      theme: default
    
  revealjs:
    slide-number: c/t
    show-slide-number: all
    transition: slide
    background-transition: fade
    chalkboard: true
    progress: true
    history: false
    scrollable: true
    width: 1600
    height: 900
    center: false

number-depth: 1
lightbox: auto